#! /bin/sh
### BEGIN INIT INFO
# Provides:          disk-backup
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Backup script
# Description:       Backup a volatile directory to disk and restore it on startup.
### END INIT INFO

# Author: Damien Tournoud <damien@commerceguys.com>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Backup to disk"
NAME=disk-backup
SCRIPTNAME=/etc/init.d/$NAME

# Destination folders.
TMPFS_DIR=/tmpfs
BACKUP_DIR=/var/backups

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Restore a backup.
#
do_start()
{
	rsync -a --delete $BACKUP_DIR/current/ $TMPFS_DIR/
	return 0
}

#
# Perform a backup of the tmpfs.
#
do_stop() {
	DIR=$BACKUP_DIR/backup-`date +%s`
	mkdir $DIR
	rsync -a $TMPFS_DIR/ $DIR
	rm $BACKUP_DIR/current || true
	ln -s $DIR $BACKUP_DIR/current
	return 0
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
